title: Interviews
email: laurel@linkedbyair.net
description: >- # this means to ignore newlines until "baseurl:"
  <a href="/index.html">Interviews</a> conducted as part of Art369b: Interactive Design and the Internet at Yale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

baseurl: interviews/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
